### ISSUE TITLE
[Feature] Animation support

### ISSUE THREAD

**Issue by NICHOLAS85** [NICHOLAS85/gebaar-libinput#13]
After seeing how https://github.com/JoseExposito/touchegg implemented smooth animations for gestures I believe a similar addition could be brought over to Gebaar!

My current plans for implementing this feature:

**Config format example**
```toml
[[swipe.commands]]
fingers = ...
down = ...
down.animation = "animation-name" (Defaults to none)

[settings]
animation.color = ...
animation.some_other_property = ...
```
For all commands, an animation can be optionally added which animates from gesture detection to gesture execution. The end goal would be to allow these animations to be drop-in/modular so people can create their own animations and share them. On a similar note, I'll look into modularizing the rest of Gebaar using https://github.com/FedeDP/libmodule. If this were achieved people could create their own gesture handles for libinput events which they could just drop in, creating a very flexible gesture daemon.

Any progress on animations will be tracked under the https://github.com/NICHOLAS85/gebaar-libinput/tree/animations branch.
The modularization of Gebaar may or may not come at a future date.
